// Regenerates the date/source tables inside README.md from src/data/ledger.json.
// `node scripts/gen-sources.mjs` writes them; `--check` fails if README has drifted.
import { readFileSync, writeFileSync } from 'node:fs';

const ledger = JSON.parse(readFileSync('src/data/ledger.json', 'utf8'));
const M = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
const fmt = (d) => { const [y, m, day] = d.split('-'); return !m ? y : !day ? `${M[m - 1]} ${y}` : `${Number(day)} ${M[m - 1]} ${y}`; };
const esc = (s) => s.replace(/\|/g, '\\|');
const entries = [...ledger.entries].sort((a, b) => a.date.localeCompare(b.date));

const main = ['| Date | Mechanism | What the date is | Primary source |', '|---|---|---|---|',
  ...entries.map((e) => `| ${fmt(e.date)} | ${esc(e.name)}${e.inClassList ? '' : ' *(added)*'} | ${esc(e.dateEvent)} | [${esc(e.source.title)}](${e.source.url}) — ${esc(e.source.authors)} (${esc(e.source.id)}) |`)].join('\n');

const roots = ['| Mechanism | Earlier root | Date | Source |', '|---|---|---|---|',
  ...entries.flatMap((e) => e.precursors.map((p) => `| ${esc(e.short)} | ${esc(p.title)} | ${fmt(p.date)} | ${p.url ? `[link](${p.url})` : 'bibliographic record'} |`))].join('\n');

const uses = ['| Mechanism | First notable use | Date | Source |', '|---|---|---|---|',
  ...entries.filter((e) => e.firstUse).map((e) => `| ${esc(e.short)} | ${esc(e.firstUse.model)} | ${fmt(e.firstUse.date)} | [link](${e.firstUse.url}) |`)].join('\n');

const block = `<!-- sources:start (generated by scripts/gen-sources.mjs from src/data/ledger.json — do not edit by hand) -->
### Timeline dates and their primary sources

${main}

### Earlier roots shown on the cards

${roots}

### First notable use (used for the "ideas wait for their bill" analysis)

${uses}
<!-- sources:end -->`;

const readme = readFileSync('README.md', 'utf8');
const next = readme.replace(/<!-- sources:start[\s\S]*?<!-- sources:end -->/, block);
if (process.argv.includes('--check')) {
  if (next !== readme) { console.error('README sources section is out of date: run node scripts/gen-sources.mjs'); process.exit(1); }
  console.log('README sources match the ledger');
} else {
  writeFileSync('README.md', next);
  console.log('README sources regenerated');
}
